all:
	g++ -std=c++2a main.cpp function.hpp area.hpp stop_criterion.hpp optimization_method.hpp Vector.hpp -o main

clan:
	clang++ -std=c++2a main.cpp function.hpp area.hpp stop_criterion.hpp optimization_method.hpp Vector.hpp -o main